name: get_it
description: Simple direct Service Locator
version: 1.0.0
author: Thomas Burkhart <burkhartsengineering@gmail.com>
homepage: https://github.com/escamoteur/get_it

environment:
  sdk: '>=2.0.0-dev<3.0.0'



dev_dependencies:
  test: 

