name: get_it
description: Simple direct Service Locator
version: 1.0.0
author: Thomas Burkhart <burkhartsengineering@gmail.com>
homepage: https://github.com/escamoteur/rx_command

environment:


dependencies:


dev_dependencies:
  flutter_test:
    sdk: flutter 

